namespace LocalLlmConsole.Models;

public sealed record AppSettings(
    string WorkspaceRoot,
    string ModelsRoot,
    string RuntimeRoot,
    string CacheRoot,
    string ThemeMode,
    string MinimizeBehavior,
    bool StartWithWindows,
    string ModelAccessMode,
    bool AutoLoadGatewayEnabled,
    int AutoLoadGatewayPort,
    string AutoLoadGatewayPolicy,
    string Host,
    bool RequireApiKeyAuth,
    string ModelApiKey,
    string ModelApiKeyBackup,
    string WslDistro,
    int Port,
    int ContextSize,
    int GpuLayers,
    bool EnableMetrics,
    int MaxLogFileSizeMb,
    int AutoUnloadIdleMinutes,
    bool DeleteRuntimeSourceAfterSuccessfulBuild,
    string ReasoningMode,
    string ReasoningFormat,
    int ReasoningBudget,
    string VisionMode,
    string VisionProjectorPath,
    int VisionImageMinTokens,
    int VisionImageMaxTokens,
    string FlashAttention,
    string CacheTypeK,
    string CacheTypeV,
    string KvOffload,
    string KvUnified,
    string ContinuousBatching,
    string JinjaMode,
    int ParallelSlots,
    int BatchSize,
    int MicroBatchSize,
    int Threads,
    string MmapMode,
    string MlockMode,
    double Temperature,
    int TopK,
    double TopP,
    double MinP,
    int MaxTokens,
    int Seed,
    int RepeatLastN,
    double RepeatPenalty,
    double PresencePenalty,
    double FrequencyPenalty,
    string RopeScaling,
    double RopeScale,
    double RopeFreqBase,
    double RopeFreqScale,
    string SpeculativeType,
    string SpecDraftModelPath,
    string MtpHeadPath,
    int SpecDraftGpuLayers,
    int SpecDraftMinTokens,
    int SpecDraftMaxTokens,
    double SpecDraftPSplit,
    double SpecDraftPMin,
    string SpecDraftCacheTypeK,
    string SpecDraftCacheTypeV,
    string CudaPackagePreference,
    string PromptCacheMode = "auto",
    int PromptCacheRamMb = 8192,
    string ContextCheckpointsMode = "auto",
    int ContextCheckpointCount = 32,
    int ContextCheckpointEveryNTokens = 256,
    string CustomParameters = "",
    string UiCulture = "en",
    string GpuMode = "auto",
    string GpuDevices = "",
    string GpuSplit = "",
    string ReasoningEffort = "default",
    string ReasoningBudgetMessage = "",
    string ReasoningPreserve = "auto",
    bool ShowOverviewModelStatus = false,
    bool ShowOverviewHardware = true,
    bool ShowOverviewSlots = false,
    bool ShowOverviewTokens = true,
    bool ShowOverviewMtpTokens = true,
    bool ShowOverviewKvCache = true,
    bool ShowOverviewLiveRuntimeLog = true,
    string RuntimeLogOrder = "newestFirst",
    bool ShowOverviewAllMetrics = false,
    bool ShowModelsHuggingFace = false,
    OverviewDashboardLayout? OverviewDashboardLayout = null,
    string ElectricityCurrencyCode = "GBP",
    double ElectricityDayRatePerKwh = 0,
    double ElectricityNightRatePerKwh = 0,
    string ElectricityNightStartLocal = "00:00",
    string ElectricityNightEndLocal = "07:00",
    bool TrackGpuEnergyWhileIdle = false)
{
    public const int DefaultContextSize = 131_072;
    public const int DefaultGpuLayers = 999;
    public const int DefaultBatchSize = 4096;
    public const string DefaultCacheType = "q8_0";
    public const double DefaultTemperature = 0.65;
    public const int DefaultMaxTokens = -1;
    public const int DefaultSeed = -1;
    public const int DefaultRepeatLastN = 64;
    public const double DefaultRepeatPenalty = 1.0;
    public const double DefaultPresencePenalty = 0.0;
    public const double DefaultFrequencyPenalty = 0.0;
    public const string DefaultRopeScaling = "auto";
    public const double DefaultRopeScale = 0.0;
    public const double DefaultRopeFreqBase = 0.0;
    public const double DefaultRopeFreqScale = 0.0;
    public const string DefaultSpeculativeType = "none";
    public const string DefaultMtpHeadPath = "";
    public const int DefaultSpecDraftGpuLayers = -1;
    public const int DefaultSpecDraftMinTokens = 0;
    public const int DefaultSpecDraftMaxTokens = 0;
    public const double DefaultSpecDraftPSplit = -1.0;
    public const double DefaultSpecDraftPMin = -1.0;
    public const int DefaultVisionImageMinTokens = 0;
    public const int DefaultVisionImageMaxTokens = 0;
    public const string DefaultCudaPackagePreference = "latest";
    public const string DefaultPromptCacheMode = "auto";
    public const int DefaultPromptCacheRamMb = 8192;
    public const string DefaultContextCheckpointsMode = "auto";
    public const int DefaultContextCheckpointCount = 32;
    public const int DefaultContextCheckpointEveryNTokens = 256;
    public const string DefaultGpuMode = "auto";

    public static AppSettings CreateDefault(string workspaceRoot) => new(
        WorkspaceRoot: workspaceRoot,
        ModelsRoot: Path.Combine(workspaceRoot, "models"),
        RuntimeRoot: Path.Combine(workspaceRoot, "runtimes"),
        CacheRoot: Path.Combine(workspaceRoot, "cache"),
        ThemeMode: "system",
        MinimizeBehavior: "taskbarOnly",
        StartWithWindows: false,
        ModelAccessMode: "local",
        AutoLoadGatewayEnabled: true,
        AutoLoadGatewayPort: 8082,
        AutoLoadGatewayPolicy: "singleActive",
        Host: "127.0.0.1",
        RequireApiKeyAuth: true,
        ModelApiKey: "",
        ModelApiKeyBackup: "",
        WslDistro: "Ubuntu-24.04",
        Port: 8081,
        ContextSize: DefaultContextSize,
        GpuLayers: DefaultGpuLayers,
        EnableMetrics: true,
        MaxLogFileSizeMb: 1,
        AutoUnloadIdleMinutes: 0,
        DeleteRuntimeSourceAfterSuccessfulBuild: true,
        ReasoningMode: "auto",
        ReasoningFormat: "auto",
        ReasoningBudget: -1,
        VisionMode: "auto",
        VisionProjectorPath: "",
        VisionImageMinTokens: DefaultVisionImageMinTokens,
        VisionImageMaxTokens: DefaultVisionImageMaxTokens,
        FlashAttention: "auto",
        CacheTypeK: DefaultCacheType,
        CacheTypeV: DefaultCacheType,
        KvOffload: "auto",
        KvUnified: "auto",
        ContinuousBatching: "on",
        JinjaMode: "auto",
        ParallelSlots: 1,
        BatchSize: DefaultBatchSize,
        MicroBatchSize: 512,
        Threads: 0,
        MmapMode: "auto",
        MlockMode: "off",
        Temperature: DefaultTemperature,
        TopK: 40,
        TopP: 0.95,
        MinP: 0.05,
        MaxTokens: DefaultMaxTokens,
        Seed: DefaultSeed,
        RepeatLastN: DefaultRepeatLastN,
        RepeatPenalty: DefaultRepeatPenalty,
        PresencePenalty: DefaultPresencePenalty,
        FrequencyPenalty: DefaultFrequencyPenalty,
        RopeScaling: DefaultRopeScaling,
        RopeScale: DefaultRopeScale,
        RopeFreqBase: DefaultRopeFreqBase,
        RopeFreqScale: DefaultRopeFreqScale,
        SpeculativeType: DefaultSpeculativeType,
        SpecDraftModelPath: "",
        MtpHeadPath: DefaultMtpHeadPath,
        SpecDraftGpuLayers: DefaultSpecDraftGpuLayers,
        SpecDraftMinTokens: DefaultSpecDraftMinTokens,
        SpecDraftMaxTokens: DefaultSpecDraftMaxTokens,
        SpecDraftPSplit: DefaultSpecDraftPSplit,
        SpecDraftPMin: DefaultSpecDraftPMin,
        SpecDraftCacheTypeK: DefaultCacheType,
        SpecDraftCacheTypeV: DefaultCacheType,
        CudaPackagePreference: DefaultCudaPackagePreference,
        PromptCacheMode: DefaultPromptCacheMode,
        PromptCacheRamMb: DefaultPromptCacheRamMb,
        ContextCheckpointsMode: DefaultContextCheckpointsMode,
        ContextCheckpointCount: DefaultContextCheckpointCount,
        ContextCheckpointEveryNTokens: DefaultContextCheckpointEveryNTokens,
        CustomParameters: "",
        UiCulture: "en",
        GpuMode: DefaultGpuMode,
        GpuDevices: "",
        GpuSplit: "");
}
