namespace LocalLlmConsole.Models;

public sealed record NamedModelLaunchProfile(
    string Id,
    string ModelId,
    string Name,
    ModelLaunchSettings Settings,
    DateTimeOffset UpdatedAt,
    bool IsDefault = false);

public sealed record ModelLaunchSettings(
    int ContextSize,
    int GpuLayers,
    bool EnableMetrics,
    string ReasoningMode,
    string ReasoningFormat,
    int ReasoningBudget,
    string VisionMode,
    string VisionProjectorPath,
    string FlashAttention,
    string CacheTypeK,
    string CacheTypeV,
    string KvOffload,
    string KvUnified,
    string ContinuousBatching,
    string JinjaMode,
    int ParallelSlots,
    int BatchSize,
    int MicroBatchSize,
    int Threads,
    string MmapMode,
    string MlockMode,
    double Temperature,
    int TopK,
    double TopP,
    double MinP,
    string RuntimeId = "",
    int Port = 0,
    int MaxTokens = AppSettings.DefaultMaxTokens,
    int Seed = AppSettings.DefaultSeed,
    int RepeatLastN = AppSettings.DefaultRepeatLastN,
    double RepeatPenalty = AppSettings.DefaultRepeatPenalty,
    double PresencePenalty = AppSettings.DefaultPresencePenalty,
    double FrequencyPenalty = AppSettings.DefaultFrequencyPenalty,
    string RopeScaling = AppSettings.DefaultRopeScaling,
    double RopeScale = AppSettings.DefaultRopeScale,
    double RopeFreqBase = AppSettings.DefaultRopeFreqBase,
    double RopeFreqScale = AppSettings.DefaultRopeFreqScale,
    string SpeculativeType = AppSettings.DefaultSpeculativeType,
    string SpecDraftModelPath = "",
    string MtpHeadPath = AppSettings.DefaultMtpHeadPath,
    int SpecDraftGpuLayers = AppSettings.DefaultSpecDraftGpuLayers,
    int SpecDraftMinTokens = AppSettings.DefaultSpecDraftMinTokens,
    int SpecDraftMaxTokens = AppSettings.DefaultSpecDraftMaxTokens,
    double SpecDraftPSplit = AppSettings.DefaultSpecDraftPSplit,
    double SpecDraftPMin = AppSettings.DefaultSpecDraftPMin,
    string SpecDraftCacheTypeK = AppSettings.DefaultCacheType,
    string SpecDraftCacheTypeV = AppSettings.DefaultCacheType,
    int VisionImageMinTokens = AppSettings.DefaultVisionImageMinTokens,
    int VisionImageMaxTokens = AppSettings.DefaultVisionImageMaxTokens,
    string PromptCacheMode = AppSettings.DefaultPromptCacheMode,
    int PromptCacheRamMb = AppSettings.DefaultPromptCacheRamMb,
    string ContextCheckpointsMode = AppSettings.DefaultContextCheckpointsMode,
    int ContextCheckpointCount = AppSettings.DefaultContextCheckpointCount,
    int ContextCheckpointEveryNTokens = AppSettings.DefaultContextCheckpointEveryNTokens,
    string CustomParameters = "",
    string GpuMode = AppSettings.DefaultGpuMode,
    string GpuDevices = "",
    string GpuSplit = "",
    string TensorBufferOverrides = "",
    string ReasoningEffort = "default",
    string ReasoningBudgetMessage = "",
    string ReasoningPreserve = "auto",
    string Host = "",
    int VulkanAllocationBlockSizeMiB = 0)
{
    public static ModelLaunchSettings FromAppSettings(AppSettings settings, string runtimeId = "") => new(
        settings.ContextSize,
        settings.GpuLayers,
        settings.EnableMetrics,
        settings.ReasoningMode,
        settings.ReasoningFormat,
        settings.ReasoningBudget,
        settings.VisionMode,
        settings.VisionProjectorPath,
        settings.FlashAttention,
        settings.CacheTypeK,
        settings.CacheTypeV,
        settings.KvOffload,
        settings.KvUnified,
        settings.ContinuousBatching,
        settings.JinjaMode,
        settings.ParallelSlots,
        settings.BatchSize,
        settings.MicroBatchSize,
        settings.Threads,
        settings.MmapMode,
        settings.MlockMode,
        settings.Temperature,
        settings.TopK,
        settings.TopP,
        settings.MinP,
        runtimeId,
        settings.Port,
        settings.MaxTokens,
        settings.Seed,
        settings.RepeatLastN,
        settings.RepeatPenalty,
        settings.PresencePenalty,
        settings.FrequencyPenalty,
        settings.RopeScaling,
        settings.RopeScale,
        settings.RopeFreqBase,
        settings.RopeFreqScale,
        settings.SpeculativeType,
        settings.SpecDraftModelPath,
        settings.MtpHeadPath,
        settings.SpecDraftGpuLayers,
        settings.SpecDraftMinTokens,
        settings.SpecDraftMaxTokens,
        settings.SpecDraftPSplit,
        settings.SpecDraftPMin,
        settings.SpecDraftCacheTypeK,
        settings.SpecDraftCacheTypeV,
        settings.VisionImageMinTokens,
        settings.VisionImageMaxTokens,
        settings.PromptCacheMode,
        settings.PromptCacheRamMb,
        settings.ContextCheckpointsMode,
        settings.ContextCheckpointCount,
        settings.ContextCheckpointEveryNTokens,
        settings.CustomParameters,
        settings.GpuMode,
        settings.GpuDevices,
        settings.GpuSplit,
        settings.TensorBufferOverrides,
        settings.ReasoningEffort,
        settings.ReasoningBudgetMessage,
        settings.ReasoningPreserve,
        settings.Host,
        settings.VulkanAllocationBlockSizeMiB);

    public AppSettings ApplyTo(AppSettings settings) => settings with
    {
        ContextSize = ContextSize,
        GpuLayers = GpuLayers,
        EnableMetrics = EnableMetrics,
        ReasoningMode = ReasoningMode,
        ReasoningFormat = ReasoningFormat,
        ReasoningBudget = ReasoningBudget,
        ReasoningEffort = ReasoningEffort ?? "default",
        ReasoningBudgetMessage = ReasoningBudgetMessage ?? "",
        ReasoningPreserve = ReasoningPreserve ?? "auto",
        VisionMode = VisionMode,
        VisionProjectorPath = VisionProjectorPath ?? "",
        FlashAttention = FlashAttention,
        CacheTypeK = CacheTypeK,
        CacheTypeV = CacheTypeV,
        KvOffload = KvOffload,
        KvUnified = KvUnified,
        ContinuousBatching = ContinuousBatching,
        JinjaMode = JinjaMode,
        ParallelSlots = ParallelSlots,
        BatchSize = BatchSize,
        MicroBatchSize = MicroBatchSize,
        Threads = Threads,
        MmapMode = MmapMode,
        MlockMode = MlockMode,
        Temperature = Temperature,
        TopK = TopK,
        TopP = TopP,
        MinP = MinP,
        Port = Port is >= 1 and <= 65535 ? Port : settings.Port,
        MaxTokens = MaxTokens,
        Seed = Seed,
        RepeatLastN = RepeatLastN,
        RepeatPenalty = RepeatPenalty,
        PresencePenalty = PresencePenalty,
        FrequencyPenalty = FrequencyPenalty,
        RopeScaling = RopeScaling,
        RopeScale = RopeScale,
        RopeFreqBase = RopeFreqBase,
        RopeFreqScale = RopeFreqScale,
        SpeculativeType = SpeculativeType,
        SpecDraftModelPath = SpecDraftModelPath,
        MtpHeadPath = MtpHeadPath ?? "",
        SpecDraftGpuLayers = SpecDraftGpuLayers,
        SpecDraftMinTokens = SpecDraftMinTokens,
        SpecDraftMaxTokens = SpecDraftMaxTokens,
        SpecDraftPSplit = SpecDraftPSplit,
        SpecDraftPMin = SpecDraftPMin,
        SpecDraftCacheTypeK = SpecDraftCacheTypeK,
        SpecDraftCacheTypeV = SpecDraftCacheTypeV,
        VisionImageMinTokens = VisionImageMinTokens,
        VisionImageMaxTokens = VisionImageMaxTokens,
        PromptCacheMode = PromptCacheMode,
        PromptCacheRamMb = PromptCacheRamMb,
        ContextCheckpointsMode = ContextCheckpointsMode,
        ContextCheckpointCount = ContextCheckpointCount,
        ContextCheckpointEveryNTokens = ContextCheckpointEveryNTokens,
        CustomParameters = CustomParameters ?? "",
        GpuMode = GpuMode ?? AppSettings.DefaultGpuMode,
        GpuDevices = GpuDevices ?? "",
        GpuSplit = GpuSplit ?? "",
        TensorBufferOverrides = TensorBufferOverrides ?? "",
        VulkanAllocationBlockSizeMiB = VulkanAllocationBlockSizeMiB,
        Host = string.IsNullOrWhiteSpace(Host) ? settings.Host : Host.Trim()
    };
}
