global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Net;
global using System.Net.Http;
global using System.Net.Sockets;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Text.RegularExpressions;
global using Microsoft.Data.Sqlite;
global using Microsoft.Win32;
global using Microsoft.Win32.SafeHandles;
global using LocalLlmConsole.Models;
global using LocalLlmConsole.Services;
global using LocalLlmConsole.ViewModels;
global using LocalLlmConsole.Localization;
global using ContextMenu = System.Windows.Controls.ContextMenu;
global using DataGrid = System.Windows.Controls.DataGrid;
global using MenuItem = System.Windows.Controls.MenuItem;
