param()

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot

# Cohesive declarative files may receive a reviewed, path-specific exception.
# Each entry must document why the content stays together, whether it is
# behavioural, and the concrete condition that should cause a future split.
$Exceptions = @{
  "src/LocalLlmConsole.App/Services/App/HelpCatalogService.cs" = [pscustomobject]@{
    Classification = "Declarative catalog"
    WarningLimit = 650
    HardLimit = 800
    Reason = "The in-app Help articles are clearer as one ordered catalog than as many pass-through services."
    SplitWhen = "Split by Help section when the catalog exceeds 800 nonblank lines or independent section ownership emerges."
    Behavioral = $false
  }
}

function Get-RepositoryRelativePath {
  param([Parameter(Mandatory = $true)][string] $Path)

  $root = [IO.Path]::GetFullPath($RepoRoot).TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar
  $fullPath = [IO.Path]::GetFullPath($Path)
  $rootUri = [Uri]::new($root)
  $pathUri = [Uri]::new($fullPath)
  return [Uri]::UnescapeDataString($rootUri.MakeRelativeUri($pathUri).ToString()).Replace("\", "/")
}

function Write-ShapeWarning {
  param(
    [Parameter(Mandatory = $true)][string] $Path,
    [Parameter(Mandatory = $true)][string] $Message
  )

  $relative = Get-RepositoryRelativePath -Path $Path
  if ($env:GITHUB_ACTIONS -eq "true") {
    Write-Host "::warning file=$relative::$Message"
  } else {
    Write-Warning "$relative`: $Message"
  }
}

function Get-SourceShape {
  param([Parameter(Mandatory = $true)][string] $Path)

  $lines = @(Get-Content -LiteralPath $Path)
  [pscustomobject]@{
    Path = $Path
    RelativePath = Get-RepositoryRelativePath -Path $Path
    TotalLines = $lines.Count
    NonBlankLines = @($lines | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }).Count
  }
}

function Test-IsGeneratedSource {
  param([Parameter(Mandatory = $true)] $Source)

  if ($Source.RelativePath -match '(?i)(\.g\.cs|\.g\.i\.cs|\.generated\.cs|\.designer\.cs)$') {
    return $true
  }

  $header = @(Get-Content -LiteralPath $Source.Path -TotalCount 5) -join "`n"
  return $header -match '(?i)<auto-generated'
}

$sourceRoots = @(
  Join-Path $RepoRoot "src"
  Join-Path $RepoRoot "tests"
)
$allSources = @($sourceRoots |
  ForEach-Object { Get-ChildItem -LiteralPath $_ -Filter *.cs -File -Recurse } |
  Where-Object { $_.FullName -notmatch '[\\/](bin|obj)[\\/]' } |
  ForEach-Object { Get-SourceShape -Path $_.FullName })
$sources = @($allSources | Where-Object { -not (Test-IsGeneratedSource -Source $_) })
$failures = [Collections.Generic.List[string]]::new()

foreach ($entry in $Exceptions.GetEnumerator()) {
  $exception = $entry.Value
  if (-not ($sources.RelativePath -contains $entry.Key)) {
    $failures.Add("Code-shape exception '$($entry.Key)' does not identify a production source file.")
  }
  if ([string]::IsNullOrWhiteSpace($exception.Classification) -or
      [string]::IsNullOrWhiteSpace($exception.Reason) -or
      [string]::IsNullOrWhiteSpace($exception.SplitWhen) -or
      $null -eq $exception.Behavioral -or
      $exception.WarningLimit -ge $exception.HardLimit) {
    $failures.Add("Code-shape exception '$($entry.Key)' must define classification, reason, split condition, behavioural status, and increasing warning/hard limits.")
  }
}

foreach ($source in $sources) {
  $isTest = $source.RelativePath.StartsWith("tests/", [StringComparison]::OrdinalIgnoreCase)
  $isMainWindow = $source.RelativePath -eq "src/LocalLlmConsole.App/MainWindow.xaml.cs" -or
    ($source.RelativePath -match '^src/LocalLlmConsole\.App/Ui/Shell/MainWindow/.*/MainWindow[^/]*\.cs$')
  $metricName = "nonblank"
  $lineCount = $source.NonBlankLines
  $warningLimit = if ($isMainWindow) { 300 } elseif ($isTest) { 650 } else { 400 }
  $hardLimit = if ($isMainWindow) { 300 } elseif ($isTest) { 800 } else { 500 }

  if ($Exceptions.ContainsKey($source.RelativePath)) {
    $exception = $Exceptions[$source.RelativePath]
    $warningLimit = $exception.WarningLimit
    $hardLimit = $exception.HardLimit
  }

  if ($lineCount -gt $hardLimit) {
    $failures.Add("$($source.RelativePath): $lineCount $metricName lines (maximum $hardLimit)")
  } elseif ($lineCount -gt $warningLimit) {
    Write-ShapeWarning -Path $source.Path -Message "$lineCount $metricName lines; review cohesion before expanding it (hard maximum $hardLimit)."
  }
}

$mainWindowSources = @($sources | Where-Object {
  $_.RelativePath -eq "src/LocalLlmConsole.App/MainWindow.xaml.cs" -or
  $_.RelativePath -match '^src/LocalLlmConsole\.App/Ui/Shell/MainWindow/.*/MainWindow[^/]*\.cs$'
})
$mainWindowNonBlank = ($mainWindowSources | Measure-Object -Property NonBlankLines -Sum).Sum
if ($mainWindowSources.Count -gt 55) {
  $failures.Add("MainWindow uses $($mainWindowSources.Count) partial files (maximum 55).")
} elseif ($mainWindowSources.Count -gt 50) {
  Write-ShapeWarning -Path (Join-Path $RepoRoot "src/LocalLlmConsole.App/MainWindow.xaml.cs") -Message "MainWindow uses $($mainWindowSources.Count) partial files (hard maximum 55)."
}
if ($mainWindowNonBlank -gt 5200) {
  $failures.Add("MainWindow contains $mainWindowNonBlank nonblank lines across partials (maximum 5200).")
} elseif ($mainWindowNonBlank -gt 5000) {
  Write-ShapeWarning -Path (Join-Path $RepoRoot "src/LocalLlmConsole.App/MainWindow.xaml.cs") -Message "MainWindow contains $mainWindowNonBlank nonblank lines across partials (hard maximum 5200)."
}

Write-Host ""
Write-Host "Largest production C# files (nonblank/physical):"
$sources | Where-Object { $_.RelativePath.StartsWith("src/", [StringComparison]::OrdinalIgnoreCase) } |
  Sort-Object NonBlankLines -Descending | Select-Object -First 15 |
  ForEach-Object { Write-Host ("{0,4}/{1,4}  {2}" -f $_.NonBlankLines, $_.TotalLines, $_.RelativePath) }
Write-Host ""
Write-Host "Largest test C# files (nonblank/physical):"
$sources | Where-Object { $_.RelativePath.StartsWith("tests/", [StringComparison]::OrdinalIgnoreCase) } |
  Sort-Object NonBlankLines -Descending | Select-Object -First 15 |
  ForEach-Object { Write-Host ("{0,4}/{1,4}  {2}" -f $_.NonBlankLines, $_.TotalLines, $_.RelativePath) }

if ($failures.Count -gt 0) {
  throw "Code-shape limits failed:`n$($failures -join [Environment]::NewLine)"
}

Write-Host "Code-shape limits passed."
